### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by benyrfg** [pixelstunde/joomla-plg-pxlcompressor#12]
Hi, 

when "keep original images" option is disabled, the drag & drop image function of TinyMCE editor not works (image is uploaded, but not shown in the editor window).

**Comment by johanpeters** [comment]
Version information joomla and pxl compressor..Personally I always use JCE editor.. works greateVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: benyrfg <notifications@github.com> Datum: 22-02-2020  13:56  (GMT+01:00) Aan: pixelstunde/joomla-plg-pxlcompressor <joomla-plg-pxlcompressor@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: [pixelstunde/joomla-plg-pxlcompressor] Drag & Drop (#12) Hi,
when "keep original images" option is enabled, the drag & drop image function of TinyMCE editor not works (image is uploaded, but not shown in the editor window).

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pixelstunde/joomla-plg-pxlcompressor/issues/12?email_source=notifications\u0026email_token=AAKYSGWHZBOOL6XYCQSRKKLREEOEHA5CNFSM4KZRIEJKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IPPJVVA",
"url": "https://github.com/pixelstunde/joomla-plg-pxlcompressor/issues/12?email_source=notifications\u0026email_token=AAKYSGWHZBOOL6XYCQSRKKLREEOEHA5CNFSM4KZRIEJKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IPPJVVA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by benyrfg** [comment]
Hi, now I use JCE+PXLCompressor, but when image upload, this error is occured:
![Screenshot - 2020-03-15T225248 213](https://user-images.githubusercontent.com/16369993/76711437-4308a880-6710-11ea-9d54-bbb67945981e.png)

Image is uploaded, but this error is still shown..
When PXL is disabled, it's OK,

Here is request details:
![Snímek obrazovky 2020-03-15 v 22 53 40 (2)](https://user-images.githubusercontent.com/16369993/76711475-b90d0f80-6710-11ea-928a-e264ab3bac01.png)
![Snímek obrazovky 2020-03-15 v 22 59 58 (2)](https://user-images.githubusercontent.com/16369993/76711481-c0341d80-6710-11ea-9887-1f56adb2b44e.png)

**Comment by johanpeters** [comment]
This was a know issue from jce editor v.2.8.6 i believe.. Update your jce editor.. it is not a pxl compressor issue..Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: benyrfg <notifications@github.com> Datum: 15-03-2020  23:01  (GMT+01:00) Aan: pixelstunde/joomla-plg-pxlcompressor <joomla-plg-pxlcompressor@noreply.github.com> Cc: johanpeters <j.peters@itics.nl>, Comment <comment@noreply.github.com> Onderwerp: Re: [pixelstunde/joomla-plg-pxlcompressor] Drag & Drop (#12) 

Hi, now I use JCE+PXLCompressor, but when image upload, this error is occured:



When PXL is disabled, it's OK,

Here is request details:







—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/pixelstunde/joomla-plg-pxlcompressor/issues/12#issuecomment-599270563",

"url": "https://github.com/pixelstunde/joomla-plg-pxlcompressor/issues/12#issuecomment-599270563",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by benyrfg** [comment]
Thanks, my JCE is up-to-date (2.8.9), it's strange when PXL is disabled, this error disappear, but I'll ask JCE support. Thanks

**Comment by johanpeters** [comment]
strange.. i had this issues with JCE... was a known issue.. and was fixed .. 
do you have the latest PXL compressor version (downloaded here).. auto update does not give you the latest version..   
i don't have any issues with JCE and PXL compressor reguarding this issue.

**Comment by benyrfg** [comment]
Hi,
yes, I have PXL 1.3, and now I have the same issue on the other website.

Joomla 3.9.18
PXL 1.3
JCE 2.8.11
Helix Ultimate framework

All latest version

Do you have some ideas?
Thanks, Petr

**Comment by johanpeters** [comment]
today i will be building a new website... incl. pxl compressor.. 
i will check on this issue.. 
i will use gantry5 framework .. 
keep you posted @benyrfg

**Comment by johanpeters** [comment]
Hello @benyrfg 
just tested it on a default helix framework template.
steps..
1 installed default helix template (quickstart)
2. update all extentions and joomla 
3. installed pxl compressor from install from web (version 1.1)
4. installed jce editor from install from web (v1.8.11)
5. enable pxl compressor with settings enabled compression etc
6. set jce editor as default editor
7. test upload image with media manager (test succesvol. image compressed)
8. test upload image on new article (jce editor) (test succesvol. images compressed)

so i can not reproduce the issue on this website.. 
can you arrange backend access to that site to have a look... ? perhaps i can see / fix the issue.

**Comment by johanpeters** [comment]
what PHP version are you running?

**Comment by benyrfg** [comment]
Hi, thank you for your involvement.

My PHP version is 7.3.6.

I have prepared backend access, how I can send you?

Thanks

**Comment by johanpeters** [comment]
Contact me johanpeters@gmail.com..

**Comment by johanpeters** [comment]
when sellecting a scall option other then default the current version is giving a error..

**Comment by pixelstunde** [comment]
@benyrfg does this error persist? please feel free to contact me via email c.friedemann@pixelstun.de

**Comment by pixelstunde** [comment]
@benyrfg Please try the latest version of master branch
